name: TheTowersGE
main: io.github.galaipa.TheTowersGE
version: 2.0
author: Galaipa 
description: TheTowers minijoko  plugina
softdepend: [WorldEdit,WorldGuard,Vault,PlayerPoints]
commands:
  thetowers:
    description: TT komando nagusia
    usage: /<command>  
    aliases: [tt]
  thetowersadmin:
    description: TT administratzaile komandoa
    usage: /<command>  
    aliases: [ttadmin]  
permissions:
  tt.user:
    description: Jokalarien komandoak erabiltzeko baimena
    default: true
  tt.admin:
    description: Administratzaileen komandoak erabiltzeko baimena
    default: op