name: TheTowersGE
main: io.github.galaipa.TheTowersGE
version: 2.5
author: Galaipa 
description: TheTowers minijoko  plugina
softdepend: [Vault,PlayerPoints,GameErauntsiaMC,Multiverse-Core]
commands:
  thetowers:
    description: TT komando nagusia
    usage: /<command>  
    aliases: [tt]
  thetowersadmin:
    description: TT administratzaile komandoa
    usage: /<command>  
    aliases: [ttadmin]  
    permission: tt.admin
permissions:
  tt.user:
    description: Jokalarien komandoak erabiltzeko baimena
    default: true
  tt.admin:
    description: Administratzaileen komandoak erabiltzeko baimena
    default: op